# api/config/packages/api_platform.yaml
api_platform:
    title: API Platform's Shopaholic
    version: 1.0.0
    description: |
        This is a shopaholic application of the [API Platform](https://api-platform.com) framework.
        [Its source code](https://github.com/couchjanus/symfony-vue) includes various examples, check it out!
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']

    swagger:
        versions: [3, 2]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        # Good cache defaults
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
