#index:
#    path: /
#    controller: App\Controller\MyClass::index

api_login_check:
    path: /api/login_check


login:
    path: /api/login
    methods: ['POST']
    defaults:
        _format: json